// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5Cm8NOdfjs0v2OSHtOOwr7edWekO4CZU',
    appId: '1:782274326261:web:b8156dee3f376d7a845fbc',
    messagingSenderId: '782274326261',
    projectId: 'infravision-5a543',
    authDomain: 'infravision-5a543.firebaseapp.com',
    storageBucket: 'infravision-5a543.appspot.com',
    measurementId: 'G-M6NLQJ1LHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ4MGesUh1VVZWoanB6wtHjWNGiLecxmw',
    appId: '1:782274326261:android:db4e8e8c74f6048c845fbc',
    messagingSenderId: '782274326261',
    projectId: 'infravision-5a543',
    storageBucket: 'infravision-5a543.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_SYnlRES6YZ-Y9sE8Q1G72FwleQ81xSI',
    appId: '1:782274326261:ios:b766fd1e85469457845fbc',
    messagingSenderId: '782274326261',
    projectId: 'infravision-5a543',
    storageBucket: 'infravision-5a543.appspot.com',
    iosBundleId: 'com.example.infravision',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_SYnlRES6YZ-Y9sE8Q1G72FwleQ81xSI',
    appId: '1:782274326261:ios:5bc2b79a0cb0c9f7845fbc',
    messagingSenderId: '782274326261',
    projectId: 'infravision-5a543',
    storageBucket: 'infravision-5a543.appspot.com',
    iosBundleId: 'com.example.infravision.RunnerTests',
  );
}
